mkdir: cannot create directory ‘experiments’: File exists
Traceback (most recent call last):
  File "train_.py", line 406, in <module>
    img, label = data_iter.next()
  File "/gpfs/share/apps/python/gpu/3.6.5/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 314, in __next__
    batch = self.collate_fn([self.dataset[i] for i in indices])
  File "/gpfs/share/apps/python/gpu/3.6.5/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 314, in <listcomp>
    batch = self.collate_fn([self.dataset[i] for i in indices])
  File "/gpfs/scratch/bilals01/test-repo/PathCNN/utils/dataloader.py", line 101, in __getitem__
    img = pil_loader(filepath)
  File "/gpfs/scratch/bilals01/test-repo/PathCNN/utils/dataloader.py", line 10, in pil_loader
    with open(path, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/gpfs/data/abl/deepomics/tsirigoslab/histopathology/Tiles/BreastTilesSorted/TCGA-BRCA/train_TCGA-BH-A18I-01A-01-TSA.ef056365-4256-4249-9632-5647ee23a6dc_13_11.jpeg'
